name: test
on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run test
      - run: bun run test:types
